### ISSUE TITLE
Make install manual issues on macOS

### ISSUE THREAD

**Issue by fharper** [shanecelis/contacts#3]
When running `sudo make install` on macOS 12.0.1, I get this error:

```
cp contacts /usr/local/bin
cp contacts.1 /usr/local/share/man/man1
cp: /usr/local/share/man/man1: No such file or directory
make: *** [install] Error 1
```

I assume it's because the man binary is in `/usr/bin/` instead of `/usr/local/share/man` on macOS.

**Comment by shanecelis** [comment]
Fixed.
